### ISSUE TITLE
Change the crate name?

### ISSUE THREAD

**Issue by Nemo157** [rustasync/async-compression-rs#1]
Current name is literally first thing that came to my mind. There may be something better, there may not, ideas welcome.

**Comment by pickfire** [comment]
How about inspiration from `serde`? **Com**pression **De**compression (`comde`). We could have a generic method to handle compression. So far as what I see for serde, there are inconsistency between different implementation of serde such as the use of `Serializer` and the methods it `impl`-ments.

**Comment by Nemo157** [comment]
One thing I would definitely want to keep is the `async`/`futures` link, this is fundamentally a crate of adaptors between existing compression libraries and async-IO (and may be deprecated in the future if the upstream libraries add support, e.g. `flate2` already has a `tokio` feature to support the `tokio-io` traits).

Which reminds me, this also needs a readme documenting what the point of the crate is.

**Comment by pickfire** [comment]
How about `acode` for **A**sync **Co**mpression **De**compression? :smile:

**Comment by secretfader** [comment]
I believe the current name adequately describes what this crate does: provide a bridge between existing compression libraries and implementations of async I/O.

If we find a better name, great. I'm completely on board. Still, I think any suggested names should clearly explain what users of the crate can expect.

**Comment by Nemo157** [comment]
Yep, I think I'm happy with keeping it as is. It's not _too_ long and is clear about what this is.

Thanks @pickfire and @secretfader!

**Comment by pickfire** [comment]
@Nemo157 But maybe we should drop the postfix `-rs` since it is redundant?

**Comment by Nemo157** [comment]
The `-rs` is only on the repo name, not the crate itself. I used that convention since I (very occasionally) work on non-Rust libraries, but since this is now part of a Rust specific org it probably makes sense to drop it.

@tirr-c do you have access to change the repo name and get rid of the `-rs`?

**Comment by tirr-c** [comment]
@Nemo157 Sure, updated!

**Comment by Nemo157** [comment]
@tirr-c thanks.

And heh, I went to update the repository url and discovered I'd already used the new one

https://github.com/rustasync/async-compression/blob/903df19e746475c56056ec080583c09f78fc51aa/Cargo.toml#L9
